set nocompatible              " be iMproved
let mapleader = ","

filetype off

runtime! plugin/sensible.vim

" Use Pathogen to install plugins 
execute pathogen#infect()
call pathogen#helptags()

filetype plugin indent on
syntax on

"colorscheme solarized
"colorscheme molokai
colorscheme peachpuff
set background=light
set background=dark

" Statusline should always be present
set laststatus=2

" For vim-airline, display all buffers when only one tab is open
let g:airline#extensions#tabline#enabled = 1
" tell vim-airline to use the powerline font glyphs.
let g:airline_powerline_fonts = 1
set encoding=utf-8
" Disable checking for extensions to see if this speeds up startup. (Nope)
"let g:airline#extensions#disable_rtp_load = 1

" CtrlP options
let g:ctrlp_clear_cache_on_exit = 0
nnoremap <leader>p :CtrlPBuffer<cr>
" CtrlP Extensions
let g:ctrlp_extensions = ['buffertag']
						", 'quickfix', 'dir', 'rtscript',
						" \ 'undo', 'line', 'changes', 'mixed', 'bookmarkdir']
" Change default file listing command.  Hopefully faster.
let g:ctrlp_user_command = 'dir %s /-n /b /s /a-d'  " Windows
" Tell ctrlp to set the language for filetype=plsql
let g:ctrlp_buftag_types = {
		\ 'plsql'	: '--language-force=SQL'
	\ }

" Easier moving between windows
" Behavior was weird using these...
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-H> <C-W><C-H>
nnoremap <C-L> <C-W><C-L>

" make the cursor stay in the middle of the screen.
nnoremap <Leader>zz :let &scrolloff=999-&scrolloff<CR> 

" Modeline
set modeline
set modelines=5

set hidden " The current buffer can be put to the background without writing to disk

set incsearch

"set fo-=t " Do no auto-wrap text using textwidth (does not apply to comments)

set nowrap
set textwidth=0		" Don't wrap lines by default
set wildmode=longest,list " At command line, complete longest common string, then list alternatives.

set backspace=indent,eol,start	" more powerful backspacing

"set tabstop=4    " Set the default tabstop
"set softtabstop=4
"set shiftwidth=4 " Set the default shift width for indents
set expandtab   " Make tabs into spaces (set by tabstop)
"set smarttab " Smarter tab levels

set showmatch  " Show matching brackets.
set matchtime=5  " Bracket blinking.
set novisualbell  " No blinking
set noerrorbells  " No noise.
set vb t_vb= " disable any beeps or flashes on error

set nolist " Display unprintable characters f12 - switches
set listchars=tab:·\ ,eol:¶,trail:·,extends:»,precedes:« " Unprintable chars mapping

set foldenable " Turn on folding
set foldmethod=marker " Fold on the marker
set foldlevel=100 " Don't autofold anything (but I can still fold manually)
set foldopen=block,hor,mark,percent,quickfix,tag " what movements open folds

" Tabs 
nnoremap <silent> <LocalLeader>[ :tabprev<CR>
nnoremap <silent> <LocalLeader>] :tabnext<CR>
" Buffers
nnoremap <silent> <LocalLeader>- :bd<CR>
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprevious<CR>

" Open the filename under the cursor.
nnoremap gf :e <cfile><CR>

" Split line(opposite to S-J joining line)
" (Interferes with using <C-J> to change windows.
"nnoremap <silent> <C-J> gEa<CR><ESC>ew 

" show/Hide hidden Chars
map <silent> <F12> :set invlist<CR>     

" Edit vimrc file.
nnoremap <leader>ev :split $MYVIMRC<cr>
" Source vimrc file
nnoremap <leader>sv :source $MYVIMRC<cr>

" Copy the full path of the file being edited to the system clipboard.
nnoremap <leader>cp :let @* = expand("%:p")<cr>

" Make the current file's directory the current directory
nnoremap <leader>cd :cd %:p:h<cr>

set ssop-=options

" Don't replace netrw functionality.
let g:NERDTreeHijackNetrw = 0
map <C-n> :NERDTreeToggle<cr>

" Tagbar
nnoremap <leader>t :TagbarToggle<cr>

let g:tagbar_autofocus = 1

let g:tagbar_type_plsql = {
	\ 'ctagstype'	: 'SQL',
    \ 'kinds' : [
        \ 'P:packages:1',
        \ 'd:prototypes',
        \ 'c:cursors',
        \ 'p:procedures',
        \ 'f:functions',
        \ 't:tables',
        \ 'r:records:1',
        \ 'F:record fields',
        \ 'L:block label',
        \ 's:subtypes',
        \ 'T:triggers',
        \ 'v:variables',
        \ 'l:local variables:1',
        \ 'i:indexes',
        \ 'e:events',
        \ 'U:publications',
        \ 'R:services',
        \ 'D:domains',
        \ 'V:views',
        \ 'n:synonyms',
        \ 'x:MobiLink Table Scripts',
        \ 'y:MobiLink Conn Scripts',
        \ 'z:MobiLink Properties',
    \ ],
\ }

cd ~/

