#!/bin/bash

#
# Purpose - display output using msgbox 
#  $1 -> set msgbox height
#  $2 -> set msgbox width
#  $3 -> set msgbox title
#
function display_output() {
    local h=${1-10}                 # box height default 10
    local w=${2-41}                 # box width default 41
    local t=${3-Output}     # box title 
    dialog --backtitle "Linux Shell Script Tutorial" --title "${t}" --clear --msgbox "$(<$OUTPUT)" ${h} ${w}
}

# Define the dialog exit status codes
: ${DIALOG_OK=0}
: ${DIALOG_CANCEL=1}
: ${DIALOG_HELP=2}
: ${DIALOG_EXTRA=3}
: ${DIALOG_ITEM_HELP=4}
: ${DIALOG_ESC=255}

#
# Main menu
#
while true
do
    # Duplicate file descriptor 1 on descriptor 3
    exec 3>&1

    ### display main menu ###
    menuchoice=$(dialog --backtitle "New Host Setup Guide" \
        --title "[ M A I N - M E N U ]" \
        --menu "Choose the TASK" 0 0 4 \
        "Add user jwheaton" "Adds jwheaton as a new user" \
        "Add user unlocker" "Adds unlocker as a new user" \
        "Exit" "Exit to the shell" \
        2>&1 1>&3 )

    exit_status=$?

    #  What task was chosen?
    case $menuchoice in
        "Add user jwheaton") echo "Add user jwheaton";;
        "Add user unlocker") echo "Add user unlocker";;
        "Exit") echo "Bye"; break;;
    esac

done

# vim:ts=4:sts=4:sw=4
