#!/bin/bash

. bin/setup-vars

#
# Purpose - display output using msgbox 
#  $1 -> set msgbox height
#  $2 -> set msgbox width
#  $3 -> set msgbox title
#
function display_output() {
    local h=${1-10}                 # box height default 10
    local w=${2-41}                 # box width default 41
    local t=${3-Output}     # box title 
    $DIALOG --backtitle "Linux Shell Script Tutorial" --title "${t}" --clear --msgbox "$(<$OUTPUT)" ${h} ${w}
}
#
# Main menu
#
while true
do
    # Duplicate file descriptor 1 on descriptor 3
    exec 3>&1

    ### display main menu ###
    menuchoice=$($DIALOG --backtitle "New Host Setup Guide" \
        --title "[ M A I N - M E N U ]" \
        --menu "Choose the TASK" 0 0 0 \
        "Add user jwheaton" "Adds jwheaton as a new user" \
        "Add user unlocker" "Adds unlocker as a new user" \
        "Run docker setup" "Sets up docker"
        "Exit" "Exit to the shell" \
        2>&1 1>&3 )

    exit_status=$?

    # Exit on cancel or escape
    case $exit_status in
        $DIALOG_CANCEL|$DIALOG_ESC) exit 0;;_
    esac

    #  What task was chosen?
    case $menuchoice in
        "Add user jwheaton") bin/adduser-jwheaton;;
        "Add user unlocker") bin/adduser-unlocker;;
        "Run docker setup") bin/setup-docker;;
        "Exit") break;;
    esac

done

# vim:ts=4:sts=4:sw=4:tw=76
